# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
  
    docker:
      - image: amitrke/java-appengine:latest

    working_directory: ~/rkerestapi

    steps:
      - checkout

      - restore_cache:
                key: rkerestapi-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
                paths:
                  - ~/.m2
                key: rkerestapi-{{ checksum "pom.xml" }}

      - run:
          name: Build and package
          command: mvn package

      - run:
             name: Dump Google Cloud Credentials to file
             command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json

      - run:
          name: Active service account
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json

      - run:
          name: Set Google cloud project id
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      #- run:
      #    name: Deploy to Google Appengine
      #    command: mvn -DskipTests appengine:deploy
