version: 2
jobs:
  build:
  
    docker:
      - image: amitrke/java-appengine:latest

    working_directory: ~/rkerestapi

    steps:
      - checkout

      - restore_cache:
          key: rkerestapi-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Build and package
          command: gradle build

      - save_cache:
          paths:
              - ~/.gradle/caches
              - ~/.gradle/wrapper
          key: rkerestapi-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json

      - run:
          name: Active service account
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json

      - run:
          name: Set Google cloud project id
          command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - run:
          name: Deploy to Google Appengine
          command: gradle appengineDeploy
